name: viva_mais
description: Aplicativo de motivação, clima, hidratação e atividades físicas.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.1.1
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.4.4

  http: ^1.2.1

  
  geolocator: ^10.1.0

  
  cached_network_image: ^3.3.1

  
  provider: ^6.1.2

  
  google_fonts: ^6.2.1
  flutter_spinkit: ^5.2.0
  flutter_slidable: ^3.1.0
  lottie: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/frases.json
